name: admin_panel
description: Professional admin panel for student management system
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core functionality
  cupertino_icons: ^1.0.8

  # Internationalization and localization
  easy_localization: ^3.0.7

  # Data handling and file operations
  excel: ^4.0.6
  file_picker: ^8.1.4

  # Charts and data visualization
  fl_chart: ^0.69.0

  # Storage and configuration
  flutter_dotenv: ^5.1.0

  # Navigation and routing
  go_router: ^14.6.1

  # UI and styling
  google_fonts: ^6.2.1

  # Internationalization and localization
  intl: ^0.20.2

  # Storage and configuration
  path_provider: ^2.0.11

  # State management
  provider: ^6.1.2

  # Storage and configuration
  shared_preferences: ^2.3.2

  # Database and authentication
  supabase_flutter: ^2.9.1

  # Data handling and file operations
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
