name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Windows
        run: flutter build windows --release

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Create NSIS installer script
        run: |
          $script = @"
          !include "MUI2.nsh"

          Name "Admin Panel"
          OutFile "admin_panel_installer.exe"
          InstallDir `$PROGRAMFILES\AdminPanel
          RequestExecutionLevel admin

          !insertmacro MUI_PAGE_WELCOME
          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_PAGE_FINISH

          !insertmacro MUI_UNPAGE_WELCOME
          !insertmacro MUI_UNPAGE_CONFIRM
          !insertmacro MUI_UNPAGE_INSTFILES
          !insertmacro MUI_UNPAGE_FINISH

          !insertmacro MUI_LANGUAGE "English"

          Section "Install"
            SetOutPath `$INSTDIR
            File /r "build\windows\x64\runner\Release\*.*"
            CreateShortcut "`$DESKTOP\Admin Panel.lnk" "`$INSTDIR\admin_panel.exe"
            CreateDirectory "`$SMPROGRAMS\Admin Panel"
            CreateShortcut "`$SMPROGRAMS\Admin Panel\Admin Panel.lnk" "`$INSTDIR\admin_panel.exe"
            CreateShortcut "`$SMPROGRAMS\Admin Panel\Uninstall.lnk" "`$INSTDIR\uninstall.exe"
            WriteUninstaller "`$INSTDIR\uninstall.exe"
          SectionEnd

          Section "Uninstall"
            Delete "`$DESKTOP\Admin Panel.lnk"
            RMDir /r "`$SMPROGRAMS\Admin Panel"
            RMDir /r "`$INSTDIR"
          SectionEnd
          "@
          $script | Out-File -FilePath "installer.nsi" -Encoding UTF8

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Package APK
        run: |
          copy "build\app\outputs\flutter-apk\app-release.apk" "admin_panel.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            admin_panel.apk
            admin_panel_installer.exe
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
